### ISSUE TITLE
Out of curiosity, what separates this lib from TS3QueryLib?

### ISSUE THREAD

**Issue by qvazzler** [nikeee/TeamSpeak3QueryAPI#10]
This lib has been around for a while: https://github.com/Scordo/TS3QueryLib.Net

Not 100% maintained so some bugs exist, but I was just wondering if you ever saw this project, and decided to take step(s) in other directions compared to it.

I want to know because I've already established a code base using aforementioned library, and currently wondering if there would be better performance / maintaining / functionality with this library.

Thanks!

**Comment by nikeee** [comment]
I was not aware of this project. This .NET library  was created simply because I wanted to port a node.js Library (node-ts) from Typescript to C#. Because the Typescript one is completely built upon Promises, the .NET port uses awaitable Tasks by design. The library you are mentioning does not seem to take that approach. Because I was not aware of that project, I cannot tell you whether it would be a good move to port.
