### ISSUE TITLE
EditChannelInfo

### ISSUE THREAD

**Issue by FeuFeuAngel** [nikeee/TeamSpeak3QueryAPI#43]
I am not expert on c# and how create API, i am using the rich client and having trouble finding some stuff, like finding the EditChannelInfo. (How get it, there is no method?)

What i find kinda stressing, that you use so many class with same fields like Editchannelinfo and Channelinfo. For each command you have your own class like Foundchannel. Is it becasue out of perfomance? Or why i cant get just the Basic Channel class?

But so far its nice to have some c# API but for me 'who dont know whats perfomant' it way to complicated. I would probaly write down all to my own methods, to get some comfy code.

**Comment by nikeee** [comment]
> What i find kinda stressing, that you use so many class with same fields like Editchannelinfo and Channelinfo.

This is done because the API returns (or requires) different data for different request types. It has nothing to do with performance.

> finding the EditChannelInfo

It is located here:
[`TeamSpeak3QueryApi.Net.Specialized.Responses.EditChannelInfo`](https://github.com/nikeee/TeamSpeak3QueryAPI/blob/c9127c526aeccbeff28bf115ce6ad56e74df359a/src/TeamSpeak3QueryApi/Specialized/Responses/EditChannelInfo.cs) (cc @SubstituteR)
