### ISSUE TITLE
Multiple channel notifications problem

### ISSUE THREAD

**Issue by AdamCzerwonka** [nikeee/TeamSpeak3QueryAPI#59]
I'm working on simple bot and I want to listen for multiple channels notfications, in order to add users to ranks etc.. I'm trying to use subscription of ClientMoved but it's only get data for first registered channel id.

**Comment by nikeee** [comment]
Is the first registered channel also the channel that the Client is in?

**Comment by AdamCzerwonka** [comment]
No, client is always placed in lobby.

**Comment by nikeee** [comment]
This may not be a bug, but rather a limitation of TeamSpeak. We should investigate this.

**Comment by AdamCzerwonka** [comment]
I've looked at ts forums from 2010 or so and found out that this might be a limitation of teamspeak. Client can only look for one channel notifications. I've tested it one telnet query it acctualy can recive notification for only one channel

**Comment by lgund** [comment]
I had the same problem. But have fixed in in the pull request. You can just create one notification for a channel but just one in the teamspeak. But there is a easy solution.

Solution
=============
Create a channelregisternotify with ID 0. That means every channel will be notified. Then you can listen by your channel if you check the target channel.

I can't give you now a sample cause I am in holidays. Give me a info if you need more help.


@nikeee: can you pls create a empty ssh branch so I could create a pull request for it?

**Comment by lgund** [comment]
Here is some information about it.

http://yat.qa/ressourcen/server-query-notify/#channel

At the end is also a interesting list of the invoke rid.

**Comment by AdamCzerwonka** [comment]
That's was exactly what I was looking for thanks.
