### ISSUE TITLE
GetClients() taking forever sometimes

### ISSUE THREAD

**Issue by igormaozao** [nikeee/TeamSpeak3QueryAPI#6]
Hello.

Sometimes when I use the GetClients (var clients= await TsClient.GetClients(GetClientOptions.Uid);) it wait forever, looks like it happens when I call the Getclients "too fast".

Any idea what could be happening? I'm testing it in a local server, so it's not a delay or something like that.

Thank you

**Comment by nikeee** [comment]
It seems like a race condition to me and should be a bug.
Until it's fixed, you can use [this extension method](http://stackoverflow.com/a/22078975) to wrap your `Task` with a timeout:
```CSharp
var clients = await client.getClients(GetClientOptions.Uid).TimeoutAfter(TimeSpan.FromSeconds(5));
```

**Comment by Sennevds** [comment]
I see that this is an old problem but I'm still having it.
I've made a tool that move's user to a certain channel. The first 2 times I can get the clients but after that it won't work anymore and times out(I have set the timeout to 10seconds which is already really long)

**Comment by nikeee** [comment]
This may have to do with #52. I'll check if this will fix this.

**Comment by Sennevds** [comment]
Hmm could be. I noticed it looks like I only get a time-out when it's called after ClientEnterView event

**Comment by nikeee** [comment]
Are you able to reproduce this issue? Can you provide a minimum reproduction?

Maybe we can work this out.

**Comment by Sennevds** [comment]
I've pushed my code to Github:
https://github.com/Sennevds/COD4_Teamspeak_sync
I've already updated my code to circumvent the problem but it happens when 
`NewClientEntered` is called it then tries to change the entered user via than ChangeUserLobby method. Here it tried(already changed that part of my code) to get the current clients and then it failed

**Comment by Sennevds** [comment]
https://gist.github.com/Sennevds/f95a1e3905cc0987c15a6ed3ea7d97bf

**Comment by Splamy** [comment]
I haven't tested your code but from my experience, _never_ call `.Result`, it's very deadlock prone.
Try changing your code block here to:
```csharp
        private static async void Test(IReadOnlyCollection<ClientEnterView> obj)
        {
            if (_client != null)
            {
                var clients = await GetClients();
            }
        }
```
While `async void` still is bad practice, it's okay for event szenarios and way better than `.Result`

**Comment by Sennevds** [comment]
Okay looks like that solves the problem of hanging connection. Thanks!

**Comment by nikeee** [comment]
Depending on the version of C#, Main can also return a `Task`.

An alternative would be to use `GetAwaiter().GetResult()`.

Is this issues solved?

**Comment by Splamy** [comment]
`GetAwaiter().GetResult()` won't fix the deadlock issue, it will just throw an exception directly (if any happens) instead of wrapping it into an AggregateException.
The problem is probably that the callback from the async event happens on the dispatch loop, which means a blocking call like `.Result` will block the dispatcher loop until the async completion event happens, but which will never happen because the dispatch loop should be the one to invoke it.

**Comment by nikeee** [comment]
Yeah, you're right. Mea culpa.
